base:
  mass: 1.4               # Base mass in Kg
  x_size: 0.24         # Dimension in x axis
  y_size: 0.20           # Dimension in y axis
  z_size: 0.09           # Dimension in z axis
  mesh: ''  # Name of the mesh files. Leave it empty ('') to have a white base.
